import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/user_profile.dart';
import 'models/goal.dart';
import 'models/recurring_purchase.dart';
import 'models/assumptions.dart';
import 'models/income_source.dart';
import 'models/account.dart';
import 'models/transaction.dart';
import 'models/sip_restore.dart';
import 'models/suggestion_history.dart';
import 'theme.dart';
import 'router.dart';
import 'finance.dart';
import 'providers/user_profile_provider.dart';
import 'utils/migration.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();

  // Register Hive TypeAdapters (generated by build_runner)
  Hive.registerAdapter(UserProfileAdapter());
  Hive.registerAdapter(GoalAdapter());
  Hive.registerAdapter(RecurringPurchaseAdapter());
  Hive.registerAdapter(AssumptionsAdapter());
  Hive.registerAdapter(IncomeSourceAdapter());
  Hive.registerAdapter(AccountAdapter());
  Hive.registerAdapter(TransactionAdapter());
  Hive.registerAdapter(SipRestoreAdapter());
  Hive.registerAdapter(SuggestionHistoryEntryAdapter());

  // Open Hive boxes
  await Hive.openBox<UserProfile>('user_profile');
  await Hive.openBox<Goal>('goals');
  await Hive.openBox<RecurringPurchase>('purchases');
  await Hive.openBox<Assumptions>('assumptions');
  await Hive.openBox<IncomeSource>('income_sources');
  await Hive.openBox<Account>('accounts');
  await Hive.openBox<Transaction>('transactions');
  await Hive.openBox<SipRestore>('sip_restore');
  await Hive.openBox<SuggestionHistoryEntry>('suggestion_history');

  // Run database migrations
  await runMigrations();

  // Verify finance engine assertions in debug mode
  assert(() {
    verifyFinanceEngine();
    return true;
  }());

  runApp(const ProviderScope(child: LedgerApp()));
}

class LedgerApp extends ConsumerWidget {
  const LedgerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final profile = ref.watch(userProfileProvider);
    final router = buildAppRouter(profile?.onboardingComplete ?? false);

    return MaterialApp.router(
      title: 'Ledger',
      debugShowCheckedModeBanner: false,
      theme: buildDarkTheme(),
      routerConfig: router,
    );
  }
}
